# Generated by Django 3.0.5 on 2020-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200402_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Seu e-mail'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Seu Github, se tiver'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='job',
            field=models.CharField(default='Dev', max_length=250, verbose_name='Seu cargo anterior'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Seu Linkedin, se tiver'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Seu nome'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Localidade que você se encontra'),
        ),
    ]
