# Generated by Django 3.0.5 on 2020-04-20 19:38

from django.db import migrations


def inset_job_name(apps, schema_editor):

    # get BankAccounts model
    JobName = apps.get_model('core', 'JobName')
    JobName.objects.create(job_name='Desenvolvedor')


def reverse_inset_job_name(apps, schema_editor):
    JobName = apps.get_model('core', 'JobName')

    try:
        JobName.objects.filter(job_name='Desenvolvedor').delete()
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200420_1915'),
    ]

    operations = [
        migrations.RunPython(inset_job_name, reverse_inset_job_name)
    ]
