# Generated by Django 3.0.5 on 2020-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200420_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='job',
            field=models.CharField(blank=True, default='Dev', max_length=250, null=True, verbose_name='Seu cargo anterior'),
        ),
    ]
